import type { Metadata } from 'next'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import './globals.css'

export const metadata: Metadata = {
  title: 'Sumcast',
  description: 'Generated by Pooria Taghdiri',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-between min-h-screen w-screen overflow-x-hidden">
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
